packages:
  - packages/*
  - example

catalog:
  '@antfu/eslint-config': ^5.0.0
  '@changesets/cli': ^2.29.5
  '@corvu/otp-field': ^0.1.4
  '@kobalte/core': 0.13.11
  '@types/lodash-es': ^4.17.12
  '@types/node': ^22.17.0
  autoprefixer: 10.4.21
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  dayjs: ^1.11.13
  eslint: ^9.32.0
  eslint-plugin-solid: ^0.14.5
  lodash-es: ^4.17.21
  postcss: 8.5.6
  rimraf: ^6.0.1
  solid-js: ^1.9.7
  tailwind-merge: 3.3.1
  tailwindcss: ^3.4.17

  tailwindcss-animate: ^1.0.7
  typescript: 5.8.3
  vite: ^7.0.6
  vite-plugin-dts: 4.5.4
  vite-plugin-solid: ^2.11.8
catalogMode: strict
