packages:
  - packages/*
  - example

catalog:
  '@antfu/eslint-config': ^5.0.0
  '@changesets/cli': ^2.29.5
  '@types/node': ^22.17.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  eslint: ^9.32.0
  eslint-plugin-solid: ^0.14.5
  rimraf: ^6.0.1
  solid-js: ^1.9.7
  typescript: 5.8.3
  vite: ^7.0.6
  vite-plugin-dts: 4.5.4
  vite-plugin-solid: ^2.11.8

catalogMode: strict
